In [133]:
import torch
import matplotlib.pyplot as plt

from tqdm import tqdm
from torchvision import datasets
from torchvision.transforms import ToTensor

In [134]:
train_data = datasets.MNIST(
    root = 'data',
    train = True,
    transform=ToTensor(),
    download=False
)

train_data = datasets.MNIST(
    root = 'data',
    train = True,
    transform=ToTensor(),
    download=False
)

In [135]:
type(train_data)

torchvision.datasets.mnist.MNIST

In [136]:
train_data.data.shape

torch.Size([60000, 28, 28])

In [137]:
test_data.data.shape

torch.Size([10000, 28, 28])

In [138]:
train_data.targets

tensor([5, 0, 4,  ..., 5, 6, 8])

In [139]:
from torch.utils.data import DataLoader

loaders = {
    
    'train': DataLoader(train_data, 
                        batch_size=64, 
                        shuffle=True, 
                        num_workers=1),
    
    'test': DataLoader(test_data, 
                       batch_size=64, 
                       shuffle=True, 
                       num_workers=1)
}

In [140]:
loaders

{'train': <torch.utils.data.dataloader.DataLoader at 0x1a1c090ed90>,
 'test': <torch.utils.data.dataloader.DataLoader at 0x1a1c0880810>}

In [141]:
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim


class CNN(nn.Module):
    
    def __init__(self):
        super(CNN, self).__init__()
        
        self.conv1 = nn.Conv2d(1, 10, kernel_size=5)
        self.conv2 = nn.Conv2d(10, 20, kernel_size=5)
        self.conv2_drop = nn.Dropout2d()
        self.fc1 = nn.Linear(320, 50)
        self.fc2 = nn.Linear(50, 10)
        
    def forward(self, x):
        x = F.relu(F.max_pool2d(self.conv1(x), 2))
        x = F.relu(F.max_pool2d(self.conv2_drop(self.conv2(x)), 2))
        x = x.view(-1, 320)
        x = F.relu(self.fc1(x))
        x = F.dropout(x, training=self.training)
        x = self.fc2(x)
        
        return F.softmax(x)

In [142]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

model = CNN().to(device)

optimizer = optim.Adam(model.parameters(), lr=0.001)

loss_fn = nn.CrossEntropyLoss()

def train(epoch):
    model.train()
    for batch_inx, (data, target) in enumerate(loaders['train']):
        data, target = data.to(device), target.to(device)
        optimizer.zero_grad()
        output = model(data)
        loss = loss_fn(output, target)
        loss.backward()
        optimizer.step()
        if batch_inx % 20 == 0:
            print(f'Train Epoch: {epoch} [{batch_inx * len(data)}/{len(loaders["train"].dataset)} ({100. * batch_inx / len(loaders["train"]):.0f}%)]\t{loss.item():.6f}')
            
def test():
    model.eval()
    
    test_loss = 0
    correct = 0
    
    with torch.no_grad():
        for data, target in loaders['test']:
            data, target = data.to(device), target.to(device)
            output = model(data)
            test_loss += loss_fn(output, target).item()
            pred = output.argmax(dim=1, keepdim=True)
            correct += pred.eq(target.view_as(pred)).sum().item()
    
    test_loss /= len(loaders['test'].dataset)
    print(f'\nTest set: Average loss: {test_loss:.4f}, Accuracy {correct}/{len(loaders["test"].dataset)} ({100. * correct / len(loaders["test"].dataset):.0f}%)\n')
    
        

In [143]:
for epoch in tqdm(range(1,11)):
    train(epoch)
    test()

  0%|                                                                                           | 0/10 [00:00<?, ?it/s]C:\Users\Stepan\AppData\Local\Temp\ipykernel_12680\3577856844.py:25: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  return F.softmax(x)


Train Epoch: 1 [0/60000 (0%)]	2.303942
Train Epoch: 1 [1280/60000 (2%)]	2.298735
Train Epoch: 1 [2560/60000 (4%)]	2.233627
Train Epoch: 1 [3840/60000 (6%)]	2.083380
Train Epoch: 1 [5120/60000 (9%)]	1.872555
Train Epoch: 1 [6400/60000 (11%)]	1.942014
Train Epoch: 1 [7680/60000 (13%)]	1.805330
Train Epoch: 1 [8960/60000 (15%)]	1.728158
Train Epoch: 1 [10240/60000 (17%)]	1.770471
Train Epoch: 1 [11520/60000 (19%)]	1.659407
Train Epoch: 1 [12800/60000 (21%)]	1.655198
Train Epoch: 1 [14080/60000 (23%)]	1.701814
Train Epoch: 1 [15360/60000 (26%)]	1.790240
Train Epoch: 1 [16640/60000 (28%)]	1.776806
Train Epoch: 1 [17920/60000 (30%)]	1.676797
Train Epoch: 1 [19200/60000 (32%)]	1.648208
Train Epoch: 1 [20480/60000 (34%)]	1.690937
Train Epoch: 1 [21760/60000 (36%)]	1.733795
Train Epoch: 1 [23040/60000 (38%)]	1.822145
Train Epoch: 1 [24320/60000 (41%)]	1.612004
Train Epoch: 1 [25600/60000 (43%)]	1.615328
Train Epoch: 1 [26880/60000 (45%)]	1.650576
Train Epoch: 1 [28160/60000 (47%)]	1.626910
Trai

 10%|████████▎                                                                          | 1/10 [00:11<01:42, 11.37s/it]


Test set: Average loss: 0.0240, Accuracy 9354/10000 (94%)

Train Epoch: 2 [0/60000 (0%)]	1.672798
Train Epoch: 2 [1280/60000 (2%)]	1.571594
Train Epoch: 2 [2560/60000 (4%)]	1.675455
Train Epoch: 2 [3840/60000 (6%)]	1.641491
Train Epoch: 2 [5120/60000 (9%)]	1.618023
Train Epoch: 2 [6400/60000 (11%)]	1.660507
Train Epoch: 2 [7680/60000 (13%)]	1.632256
Train Epoch: 2 [8960/60000 (15%)]	1.580621
Train Epoch: 2 [10240/60000 (17%)]	1.565180
Train Epoch: 2 [11520/60000 (19%)]	1.602217
Train Epoch: 2 [12800/60000 (21%)]	1.578446
Train Epoch: 2 [14080/60000 (23%)]	1.601257
Train Epoch: 2 [15360/60000 (26%)]	1.606237
Train Epoch: 2 [16640/60000 (28%)]	1.595900
Train Epoch: 2 [17920/60000 (30%)]	1.612998
Train Epoch: 2 [19200/60000 (32%)]	1.621710
Train Epoch: 2 [20480/60000 (34%)]	1.622534
Train Epoch: 2 [21760/60000 (36%)]	1.590150
Train Epoch: 2 [23040/60000 (38%)]	1.632145
Train Epoch: 2 [24320/60000 (41%)]	1.618531
Train Epoch: 2 [25600/60000 (43%)]	1.597469
Train Epoch: 2 [26880/60000 (45%

 20%|████████████████▌                                                                  | 2/10 [00:22<01:31, 11.40s/it]


Test set: Average loss: 0.0237, Accuracy 9499/10000 (95%)

Train Epoch: 3 [0/60000 (0%)]	1.649640
Train Epoch: 3 [1280/60000 (2%)]	1.606552
Train Epoch: 3 [2560/60000 (4%)]	1.584279
Train Epoch: 3 [3840/60000 (6%)]	1.571469
Train Epoch: 3 [5120/60000 (9%)]	1.657687
Train Epoch: 3 [6400/60000 (11%)]	1.539779
Train Epoch: 3 [7680/60000 (13%)]	1.662980
Train Epoch: 3 [8960/60000 (15%)]	1.580496
Train Epoch: 3 [10240/60000 (17%)]	1.561368
Train Epoch: 3 [11520/60000 (19%)]	1.530715
Train Epoch: 3 [12800/60000 (21%)]	1.506328
Train Epoch: 3 [14080/60000 (23%)]	1.614850
Train Epoch: 3 [15360/60000 (26%)]	1.533400
Train Epoch: 3 [16640/60000 (28%)]	1.530374
Train Epoch: 3 [17920/60000 (30%)]	1.525795
Train Epoch: 3 [19200/60000 (32%)]	1.544827
Train Epoch: 3 [20480/60000 (34%)]	1.597408
Train Epoch: 3 [21760/60000 (36%)]	1.566250
Train Epoch: 3 [23040/60000 (38%)]	1.527315
Train Epoch: 3 [24320/60000 (41%)]	1.538024
Train Epoch: 3 [25600/60000 (43%)]	1.532245
Train Epoch: 3 [26880/60000 (45%

 30%|████████████████████████▉                                                          | 3/10 [00:34<01:20, 11.52s/it]


Test set: Average loss: 0.0236, Accuracy 9561/10000 (96%)

Train Epoch: 4 [0/60000 (0%)]	1.540378
Train Epoch: 4 [1280/60000 (2%)]	1.605538
Train Epoch: 4 [2560/60000 (4%)]	1.537484
Train Epoch: 4 [3840/60000 (6%)]	1.641250
Train Epoch: 4 [5120/60000 (9%)]	1.547334
Train Epoch: 4 [6400/60000 (11%)]	1.542631
Train Epoch: 4 [7680/60000 (13%)]	1.555878
Train Epoch: 4 [8960/60000 (15%)]	1.526408
Train Epoch: 4 [10240/60000 (17%)]	1.522174
Train Epoch: 4 [11520/60000 (19%)]	1.508000
Train Epoch: 4 [12800/60000 (21%)]	1.580384
Train Epoch: 4 [14080/60000 (23%)]	1.625147
Train Epoch: 4 [15360/60000 (26%)]	1.550778
Train Epoch: 4 [16640/60000 (28%)]	1.537930
Train Epoch: 4 [17920/60000 (30%)]	1.507899
Train Epoch: 4 [19200/60000 (32%)]	1.571976
Train Epoch: 4 [20480/60000 (34%)]	1.523017
Train Epoch: 4 [21760/60000 (36%)]	1.495080
Train Epoch: 4 [23040/60000 (38%)]	1.570826
Train Epoch: 4 [24320/60000 (41%)]	1.620514
Train Epoch: 4 [25600/60000 (43%)]	1.554574
Train Epoch: 4 [26880/60000 (45%

 40%|█████████████████████████████████▏                                                 | 4/10 [00:46<01:09, 11.57s/it]


Test set: Average loss: 0.0235, Accuracy 9626/10000 (96%)

Train Epoch: 5 [0/60000 (0%)]	1.543742
Train Epoch: 5 [1280/60000 (2%)]	1.513836
Train Epoch: 5 [2560/60000 (4%)]	1.515207
Train Epoch: 5 [3840/60000 (6%)]	1.529292
Train Epoch: 5 [5120/60000 (9%)]	1.559328
Train Epoch: 5 [6400/60000 (11%)]	1.572274
Train Epoch: 5 [7680/60000 (13%)]	1.526994
Train Epoch: 5 [8960/60000 (15%)]	1.500329
Train Epoch: 5 [10240/60000 (17%)]	1.516742
Train Epoch: 5 [11520/60000 (19%)]	1.546535
Train Epoch: 5 [12800/60000 (21%)]	1.547122
Train Epoch: 5 [14080/60000 (23%)]	1.522507
Train Epoch: 5 [15360/60000 (26%)]	1.518642
Train Epoch: 5 [16640/60000 (28%)]	1.540160
Train Epoch: 5 [17920/60000 (30%)]	1.573519
Train Epoch: 5 [19200/60000 (32%)]	1.530619
Train Epoch: 5 [20480/60000 (34%)]	1.588840
Train Epoch: 5 [21760/60000 (36%)]	1.598776
Train Epoch: 5 [23040/60000 (38%)]	1.566721
Train Epoch: 5 [24320/60000 (41%)]	1.553008
Train Epoch: 5 [25600/60000 (43%)]	1.548534
Train Epoch: 5 [26880/60000 (45%

 50%|█████████████████████████████████████████▌                                         | 5/10 [00:57<00:58, 11.67s/it]


Test set: Average loss: 0.0235, Accuracy 9674/10000 (97%)

Train Epoch: 6 [0/60000 (0%)]	1.585848
Train Epoch: 6 [1280/60000 (2%)]	1.542219
Train Epoch: 6 [2560/60000 (4%)]	1.488479
Train Epoch: 6 [3840/60000 (6%)]	1.562305
Train Epoch: 6 [5120/60000 (9%)]	1.569104
Train Epoch: 6 [6400/60000 (11%)]	1.544394
Train Epoch: 6 [7680/60000 (13%)]	1.484249
Train Epoch: 6 [8960/60000 (15%)]	1.545651
Train Epoch: 6 [10240/60000 (17%)]	1.525929
Train Epoch: 6 [11520/60000 (19%)]	1.494399
Train Epoch: 6 [12800/60000 (21%)]	1.579284
Train Epoch: 6 [14080/60000 (23%)]	1.584783
Train Epoch: 6 [15360/60000 (26%)]	1.541160
Train Epoch: 6 [16640/60000 (28%)]	1.544684
Train Epoch: 6 [17920/60000 (30%)]	1.513523
Train Epoch: 6 [19200/60000 (32%)]	1.477258
Train Epoch: 6 [20480/60000 (34%)]	1.596517
Train Epoch: 6 [21760/60000 (36%)]	1.534298
Train Epoch: 6 [23040/60000 (38%)]	1.605464
Train Epoch: 6 [24320/60000 (41%)]	1.558412
Train Epoch: 6 [25600/60000 (43%)]	1.521818
Train Epoch: 6 [26880/60000 (45%

 60%|█████████████████████████████████████████████████▊                                 | 6/10 [01:09<00:47, 11.78s/it]


Test set: Average loss: 0.0235, Accuracy 9666/10000 (97%)

Train Epoch: 7 [0/60000 (0%)]	1.579224
Train Epoch: 7 [1280/60000 (2%)]	1.568027
Train Epoch: 7 [2560/60000 (4%)]	1.526117
Train Epoch: 7 [3840/60000 (6%)]	1.516035
Train Epoch: 7 [5120/60000 (9%)]	1.510271
Train Epoch: 7 [6400/60000 (11%)]	1.497651
Train Epoch: 7 [7680/60000 (13%)]	1.478838
Train Epoch: 7 [8960/60000 (15%)]	1.525220
Train Epoch: 7 [10240/60000 (17%)]	1.545123
Train Epoch: 7 [11520/60000 (19%)]	1.493659
Train Epoch: 7 [12800/60000 (21%)]	1.549420
Train Epoch: 7 [14080/60000 (23%)]	1.561071
Train Epoch: 7 [15360/60000 (26%)]	1.506989
Train Epoch: 7 [16640/60000 (28%)]	1.549305
Train Epoch: 7 [17920/60000 (30%)]	1.552818
Train Epoch: 7 [19200/60000 (32%)]	1.521793
Train Epoch: 7 [20480/60000 (34%)]	1.507555
Train Epoch: 7 [21760/60000 (36%)]	1.494675
Train Epoch: 7 [23040/60000 (38%)]	1.496088
Train Epoch: 7 [24320/60000 (41%)]	1.535065
Train Epoch: 7 [25600/60000 (43%)]	1.538229
Train Epoch: 7 [26880/60000 (45%

 70%|██████████████████████████████████████████████████████████                         | 7/10 [01:21<00:35, 11.70s/it]


Test set: Average loss: 0.0234, Accuracy 9710/10000 (97%)

Train Epoch: 8 [0/60000 (0%)]	1.551824
Train Epoch: 8 [1280/60000 (2%)]	1.489707
Train Epoch: 8 [2560/60000 (4%)]	1.544455
Train Epoch: 8 [3840/60000 (6%)]	1.510564
Train Epoch: 8 [5120/60000 (9%)]	1.539298
Train Epoch: 8 [6400/60000 (11%)]	1.486353
Train Epoch: 8 [7680/60000 (13%)]	1.545785
Train Epoch: 8 [8960/60000 (15%)]	1.510339
Train Epoch: 8 [10240/60000 (17%)]	1.516969
Train Epoch: 8 [11520/60000 (19%)]	1.478125
Train Epoch: 8 [12800/60000 (21%)]	1.595611
Train Epoch: 8 [14080/60000 (23%)]	1.535004
Train Epoch: 8 [15360/60000 (26%)]	1.560577
Train Epoch: 8 [16640/60000 (28%)]	1.508769
Train Epoch: 8 [17920/60000 (30%)]	1.571199
Train Epoch: 8 [19200/60000 (32%)]	1.607273
Train Epoch: 8 [20480/60000 (34%)]	1.502938
Train Epoch: 8 [21760/60000 (36%)]	1.517553
Train Epoch: 8 [23040/60000 (38%)]	1.597540
Train Epoch: 8 [24320/60000 (41%)]	1.538061
Train Epoch: 8 [25600/60000 (43%)]	1.582832
Train Epoch: 8 [26880/60000 (45%

 80%|██████████████████████████████████████████████████████████████████▍                | 8/10 [01:33<00:23, 11.74s/it]


Test set: Average loss: 0.0234, Accuracy 9734/10000 (97%)

Train Epoch: 9 [0/60000 (0%)]	1.564430
Train Epoch: 9 [1280/60000 (2%)]	1.524496
Train Epoch: 9 [2560/60000 (4%)]	1.556342
Train Epoch: 9 [3840/60000 (6%)]	1.517770
Train Epoch: 9 [5120/60000 (9%)]	1.486652
Train Epoch: 9 [6400/60000 (11%)]	1.530646
Train Epoch: 9 [7680/60000 (13%)]	1.517375
Train Epoch: 9 [8960/60000 (15%)]	1.506211
Train Epoch: 9 [10240/60000 (17%)]	1.557037
Train Epoch: 9 [11520/60000 (19%)]	1.493624
Train Epoch: 9 [12800/60000 (21%)]	1.542131
Train Epoch: 9 [14080/60000 (23%)]	1.524093
Train Epoch: 9 [15360/60000 (26%)]	1.508085
Train Epoch: 9 [16640/60000 (28%)]	1.576309
Train Epoch: 9 [17920/60000 (30%)]	1.549892
Train Epoch: 9 [19200/60000 (32%)]	1.495516
Train Epoch: 9 [20480/60000 (34%)]	1.511778
Train Epoch: 9 [21760/60000 (36%)]	1.564602
Train Epoch: 9 [23040/60000 (38%)]	1.484360
Train Epoch: 9 [24320/60000 (41%)]	1.602854
Train Epoch: 9 [25600/60000 (43%)]	1.478404
Train Epoch: 9 [26880/60000 (45%

 90%|██████████████████████████████████████████████████████████████████████████▋        | 9/10 [01:44<00:11, 11.71s/it]


Test set: Average loss: 0.0234, Accuracy 9721/10000 (97%)

Train Epoch: 10 [0/60000 (0%)]	1.544639
Train Epoch: 10 [1280/60000 (2%)]	1.528710
Train Epoch: 10 [2560/60000 (4%)]	1.529637
Train Epoch: 10 [3840/60000 (6%)]	1.516713
Train Epoch: 10 [5120/60000 (9%)]	1.524585
Train Epoch: 10 [6400/60000 (11%)]	1.499704
Train Epoch: 10 [7680/60000 (13%)]	1.526732
Train Epoch: 10 [8960/60000 (15%)]	1.493801
Train Epoch: 10 [10240/60000 (17%)]	1.512568
Train Epoch: 10 [11520/60000 (19%)]	1.489039
Train Epoch: 10 [12800/60000 (21%)]	1.598248
Train Epoch: 10 [14080/60000 (23%)]	1.554094
Train Epoch: 10 [15360/60000 (26%)]	1.529904
Train Epoch: 10 [16640/60000 (28%)]	1.523878
Train Epoch: 10 [17920/60000 (30%)]	1.601758
Train Epoch: 10 [19200/60000 (32%)]	1.526245
Train Epoch: 10 [20480/60000 (34%)]	1.542119
Train Epoch: 10 [21760/60000 (36%)]	1.567714
Train Epoch: 10 [23040/60000 (38%)]	1.511817
Train Epoch: 10 [24320/60000 (41%)]	1.463553
Train Epoch: 10 [25600/60000 (43%)]	1.488443
Train Epoch

100%|██████████████████████████████████████████████████████████████████████████████████| 10/10 [01:56<00:00, 11.68s/it]


Test set: Average loss: 0.0234, Accuracy 9731/10000 (97%)



In [144]:
device

device(type='cuda')

In [145]:
torch_tenzor = torch.randn(3,4,5, device=device)
print(torch_tenzor.shape,'\n', torch_tenzor)

torch.Size([3, 4, 5]) 
 tensor([[[-1.3546, -0.6444, -0.8354,  3.0058, -3.0112],
         [-0.3302, -0.3510,  0.4539, -1.2193,  1.7731],
         [ 0.8176,  0.5375,  0.9117, -1.5843, -0.0984],
         [-0.9933,  0.0553,  0.1760,  0.1377, -0.4918]],

        [[-0.0156,  0.1002,  2.0079, -1.2036, -0.3101],
         [ 0.5766, -0.4363, -0.6329, -0.6787, -0.2054],
         [ 0.4182, -0.1660,  1.3155,  1.0740, -0.3726],
         [ 0.1030,  0.3462, -0.0268, -0.8327, -1.4514]],

        [[-1.2844, -0.1269, -1.3423, -0.9462, -0.1918],
         [-0.6804, -0.3643,  1.3263, -1.6483, -0.8329],
         [-0.4506, -1.6685,  0.4311, -0.3694, -0.2759],
         [-0.2191,  0.0126,  0.3336,  0.2443, -0.6055]]], device='cuda:0')


In [146]:
torch_tenzor = torch_tenzor.view(6,10)
torch_tenzor

tensor([[-1.3546, -0.6444, -0.8354,  3.0058, -3.0112, -0.3302, -0.3510,  0.4539,
         -1.2193,  1.7731],
        [ 0.8176,  0.5375,  0.9117, -1.5843, -0.0984, -0.9933,  0.0553,  0.1760,
          0.1377, -0.4918],
        [-0.0156,  0.1002,  2.0079, -1.2036, -0.3101,  0.5766, -0.4363, -0.6329,
         -0.6787, -0.2054],
        [ 0.4182, -0.1660,  1.3155,  1.0740, -0.3726,  0.1030,  0.3462, -0.0268,
         -0.8327, -1.4514],
        [-1.2844, -0.1269, -1.3423, -0.9462, -0.1918, -0.6804, -0.3643,  1.3263,
         -1.6483, -0.8329],
        [-0.4506, -1.6685,  0.4311, -0.3694, -0.2759, -0.2191,  0.0126,  0.3336,
          0.2443, -0.6055]], device='cuda:0')

In [147]:
torch_inttenzor = torch.randint(10, (10,), device=device)
torch_inttenzor

tensor([9, 2, 5, 6, 2, 8, 5, 9, 9, 8], device='cuda:0')

In [148]:
result_tenzor = torch_tenzor * torch_inttenzor
result_tenzor

tensor([[-12.1915,  -1.2888,  -4.1769,  18.0346,  -6.0225,  -2.6418,  -1.7552,
           4.0854, -10.9737,  14.1846],
        [  7.3585,   1.0751,   4.5587,  -9.5057,  -0.1967,  -7.9462,   0.2763,
           1.5844,   1.2395,  -3.9340],
        [ -0.1403,   0.2005,  10.0395,  -7.2215,  -0.6203,   4.6132,  -2.1815,
          -5.6963,  -6.1081,  -1.6430],
        [  3.7642,  -0.3320,   6.5774,   6.4437,  -0.7453,   0.8236,   1.7311,
          -0.2410,  -7.4941, -11.6112],
        [-11.5598,  -0.2538,  -6.7114,  -5.6770,  -0.3835,  -5.4433,  -1.8216,
          11.9371, -14.8348,  -6.6634],
        [ -4.0556,  -3.3371,   2.1553,  -2.2164,  -0.5518,  -1.7530,   0.0630,
           3.0023,   2.1990,  -4.8438]], device='cuda:0')

In [149]:
result_tenzor.shape
result_tenzor_T = result_tenzor.t()
print(result_tenzor.shape, result_tenzor_T.shape)

torch.Size([6, 10]) torch.Size([10, 6])


In [150]:
result = torch.matmul(reshaped_tensor.to(device=device), result_tenzor_T.to(device))
result.shape

torch.Size([6, 6])

In [151]:
x = torch.ones(3, requires_grad=True)
z = torch.ones(3, requires_grad=True)
t = torch.ones(3, requires_grad=True)

y = x**3 + z - 75*t #(1, 0.5, 2)
y.backward(torch.ones_like(y))

grad_x = x.grad
grad_z = z.grad
grad_t = t.grad


print("Градиенты:")
print("По x:", grad_x)
print("По z:", grad_z)
print("По t:", grad_t)

Градиенты:
По x: tensor([3., 3., 3.])
По z: tensor([1., 1., 1.])
По t: tensor([-75., -75., -75.])


In [152]:
onec_tenzor_to_numpy = torch.ones(5,6).numpy()
onec_tenzor_to_numpy

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]], dtype=float32)